import "@/web3/styles.css";

import { AppCacheProvider } from "@mui/material-nextjs/v14-pagesRouter";
import type { AppProps } from "next/app";
import Head from "next/head";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "@/theme";
import { Web3Provider } from "@/web3/Web3Provider";
import { SnackbarProvider } from "notistack";
import { Layout } from "@/components/layout/Layout";
import { Analytics } from "@vercel/analytics/react";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppCacheProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <SnackbarProvider>
            <Web3Provider>
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </Web3Provider>
          </SnackbarProvider>
        </ThemeProvider>
      </AppCacheProvider>
      <Analytics />
    </>
  );
}
