import { AppCacheProvider } from "@mui/material-nextjs/v14-pagesRouter";
import type { AppProps } from "next/app";
import Head from "next/head";
import localFont from "next/font/local";
import { createTheme, CssBaseline, ThemeProvider } from "@mui/material";

const font = localFont({
  src: [
    {
      path: "../font/MatterSQ-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../font/MatterSQ-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../font/MatterSQ-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/MatterSQ-RegularItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../font/MatterSQ-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../font/MatterSQ-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../font/MatterSQ-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../font/MatterSQ-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../font/MatterSQ-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../font/MatterSQ-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
});

const theme = createTheme({
  components: {
    MuiCssBaseline: {
      styleOverrides: {
        "::-webkit-scrollbar": {
          background: "transparent",
          width: "8px",
          height: "8px",
        },
        "::-webkit-scrollbar-track": {
          borderRadius: "10px",
        },
        "::-webkit-scrollbar-thumb": {
          background: "#A2A2DC",
          padding: "1px",
          borderRadius: "10px",
        },
      },
    },
  },
  typography: {
    ...font.style,
  },
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppCacheProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Component {...pageProps} />
        </ThemeProvider>
      </AppCacheProvider>
    </>
  );
}
