[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
structured-product = "GYFmKqbpYHUrML3BstU9VUnVdEE6ho9tzVJzs1DAR5iz"
transferhook = "6sGAcb6vw8bhcVNPv5pMEhr3dXyeYoX2X89S3NkEaaJP"
treasury-wallet = "3DUqJ4S1dUoKzC77NmJXq2wiDqwR3NoNkEwtkFU4SaY3"

[programs.devnet]
structured-product = "GYFmKqbpYHUrML3BstU9VUnVdEE6ho9tzVJzs1DAR5iz"
transferhook = "6sGAcb6vw8bhcVNPv5pMEhr3dXyeYoX2X89S3NkEaaJP"
treasury-wallet = "3DUqJ4S1dUoKzC77NmJXq2wiDqwR3NoNkEwtkFU4SaY3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/structured-product.ts"
