[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
structured-product = "GYFmKqbpYHUrML3BstU9VUnVdEE6ho9tzVJzs1DAR5iz"
transferhook = "7aeu4HRHR4UwQndRDyh5f7nMwgxgH3rrtLgRntxdivZw"
treasury-wallet = "3DUqJ4S1dUoKzC77NmJXq2wiDqwR3NoNkEwtkFU4SaY3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/daniel/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/structured-product.ts"
