name: Master - Push
on:
  push:
    branches:
      - master

jobs:
  build-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.1.0"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install  --frozen-lockfile
      - name: Build programs typescript
        run: pnpm run --filter programs build:ts
      - name: Build frontend
        run: pnpm run --filter ./frontend build
        env:
          NEXT_PUBLIC_API_URL: "localhost:3000"
          NEXT_PUBLIC_STRUCTURED_PRODUCT_PROGRAM_ID: ${{secrets.STRUCTURED_PRODUCT_PROGRAM_ID}}
          NEXT_PUBLIC_TREASURY_WALLET_PROGRAM_ID: ${{secrets.TREASURY_WALLET_PROGRAM_ID}}
          NEXT_PUBLIC_TRANSFER_SNAPSHOT_HOOK_PROGRAM_ID: ${{secrets.TRANSFER_SNAPSHOT_HOOK_PROGRAM_ID}}
          NEXT_PUBLIC_TERMS_AND_CONDITIONS_URL: ""
          NEXT_PUBLIC_PRIVACY_POLICY_URL: ""
      - name: Build backend
        run: pnpm run --filter backend build
  build-anchor:
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.29.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create config directory
        run: mkdir -p ~/.config/solana
      - name: Set rust version
        run: rustup default stable
      - name: Set solana key from secret
        run: echo ${{ secrets.SOLANA_PRIVATE_KEY }} > ~/.config/solana/id.json
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install pnpm dependencies
        run: pnpm install
      - name: Build
        run: pnpm run --filter programs build
      # - name: Test
      #   run: pnpm run --filter programs test
      - name: Upgrade structured product program
        run: pnpm run --filter programs upgrade:structured-product:devnet
      - name: Upgrade treasury wallet program
        run: pnpm run --filter programs upgrade:treasury-wallet:devnet
      - name: Upgrade transfer hook program
        run: pnpm run --filter programs upgrade:transferhook:devnet
  deploy-backend-to-cloud-run:
    runs-on: ubuntu-latest
    needs: [build-typescript]
    steps:
      - uses: actions/checkout@v4
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Authenticate Docker to Google Cloud
        run: gcloud auth configure-docker europe-west6-docker.pkg.dev --quiet
      - name: Build and Push Docker image to Artifact Registry
        run: |
          docker build -t europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/staging/hackathon-backend:${{github.sha}} -f ./docker/backend/Dockerfile .
          docker push europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/staging/hackathon-backend:${{github.sha}}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy hackathon-backend-service \
            --image europe-west6-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/staging/hackathon-backend:${{github.sha}} \
            --platform managed \
            --region europe-west6 \
            --set-env-vars PROVIDER_RPC_URL=https://api.devnet.solana.com \
            --set-env-vars STRUCTURED_PRODUCT_PROGRAM_ID=${{secrets.STRUCTURED_PRODUCT_PROGRAM_ID}} \
            --set-env-vars TREASURY_WALLET_PROGRAM_ID=${{secrets.TREASURY_WALLET_PROGRAM_ID}} \
            --set-env-vars TRANSFER_HOOK_PROGRAM_ID=${{secrets.TRANSFER_HOOK_PROGRAM_ID}} \
            --set-env-vars ^@^ISSUER_SECRET_KEY=${{secrets.ISSUER_SECRET_KEY}} \
            --set-env-vars ^@^SERVER_SECRET_KEY=${{secrets.SERVER_SECRET_KEY}} \
            --set-env-vars PAYMENT_TOKEN_MINT_ADDRESS=${{secrets.PAYMENT_TOKEN_MINT_ADDRESS}} \
